### ISSUE TITLE
This example is not available

### ISSUE THREAD

**Issue by RicardoScofileld** [RohanDas28/Go-Daddy-email-sender-python#2]
use right username and password can login on website, but put it in code, rasie exception.

    raise SMTPServerDisconnected("Connection unexpectedly closed")
smtplib.SMTPServerDisconnected: Connection unexpectedly closed

**Comment by RohanDas28** [comment]
Fixed!

**Comment by RicardoScofileld** [comment]
> Fixed!

god!!!, my question is I use username and password can login https://email.godaddy.com/. But I replace the username and password in code, cannot send email. so, guys, do you know why, Is need to set up some setting in godaday? Thank you, ORZ

**Comment by RohanDas28** [comment]
you need to enable smtp auth first
https://www.godaddy.com/en-in/help/enable-smtp-authentication-40981

**Comment by RicardoScofileld** [comment]
> Owner

Thank you very much, ORZ.
